### ISSUE TITLE
Gibbs Energy

### ISSUE THREAD

**Issue by chtchelkatchev** [ICAMS/calphy#146]
Thanks a lot for the good thermodynamic integration software package. A lot of work has been done. The program is in high demand. However, there are a number of issues related to the operation of the program. 
1) First of all, let's look at the examples in the documentation. Example 12. Calculation of Cp from free energy. The formula for entropy is inaccurate. Entropy at constant pressure is expressed not in terms of free energy F, but in terms of the Gibbs potential G (see L D Landau, E.M. Lifshitz, vol.5): S(T,P)=-\frac{\partial G(T,P)}{\partial T}.
2) At a melting transition pressure is equal in both phases, but density does not. May be in example 3 and 4 better take G(T,P) rather than F(T,V(T,P)).  I understand that taking F formally is ok, but G seems more natural because it depends on "good" parameters for a phase transition (T,P).  Or I do not understand smth? By the way, G is used in DPTI thermodynamic integration code of the deepmodeling team for phase transition investigations.

**Comment by srmnitc** [comment]
@chtchelkatchev Thanks for the points!

1. Thanks for spotting this. Correct, I need to make the changes. I will keep this issue open to keep track.
2. Also correct; the reason for using F was simply because the calculations are zero pressure, therefore F = G. If one turns on the pressure, automatically G is calculated, instead of F.

**Comment by srmnitc** [comment]
Fixed in #148
